import { projectImages } from './images'

export const realProjects = [
  {
    title: 'Meulemanstraat 34',
    slug: 'meulemanstraat-34',
    category: 'Totaalrenovatie',
    location: 'Sint-Lievens-Houtem',
    year: 2024,
    featured: true,
    sortOrder: 1,
    projectType: 'Totaalrenovatie',
    duration: '7 maanden',
    surface: '280 m²',
    completionDate: '2024',
    shortDescription: 'Volledige transformatie van een onbewoonbaar verklaarde rijwoning tot een modern pareltje met witte gevel en strak interieur.',
    challengeText: 'Deze klassieke bakstenen rijwoning had haar beste tijd gehad. De gevel was verouderd, het interieur was gedateerd met een oude trap en versleten vloeren. De eigenaar droomde van een complete metamorfose — een moderne woning met behoud van het karakter van het pand.',
    approachText: 'We pakten dit project aan als een volledige totaalrenovatie. Eerst werd het interieur volledig gestript tot op de ruwbouw. Vervolgens volgde een grondige heropbouw: nieuwe vloeren in eiken parket en grijze tegels, strakke witte wanden met ingebouwde spots, en moderne deuren. De gevel werd volledig vernieuwd met een strakke witte afwerking en een nieuw donker dak. De oprit werd heraangelegd met moderne klinkers en er kwam een nieuwe garage.',
    resultText: 'Het resultaat is een woning die niet meer te herkennen is. De witte gevel straalt moderniteit uit, terwijl het interieur warmte en comfort biedt dankzij de eiken vloeren en strakke afwerking. Een totaaltransformatie waar de eigenaar trots op mag zijn.',
    mainImage: projectImages.meulemanstraat.main,
    images: {
      before: projectImages.meulemanstraat.before,
      after: projectImages.meulemanstraat.after,
    },
  },
  {
    title: 'Renovatie Oostende',
    slug: 'renovatie-oostende',
    category: 'Renovatie',
    location: 'Oostende',
    year: 2023,
    featured: false,
    sortOrder: 2,
    projectType: 'Renovatie',
    duration: '5 maanden',
    surface: '150 m²',
    completionDate: '2023',
    shortDescription: 'Interieur renovatie en dakwerken van een gezinswoning aan de Belgische kust.',
    challengeText: 'De eigenaars van deze woning in Oostende wilden hun leefruimte volledig vernieuwen en tegelijk het dak aanpakken dat aan vervanging toe was. De uitdaging lag in het combineren van interieurwerken met dakwerken, terwijl het gezin zo min mogelijk hinder ondervond.',
    approachText: 'We startten met de dakwerken: nieuwe pannen, onderdak met OSB-platen en waterdichting. Parallel werkten we aan het interieur. Vloerverwarming werd ingestoken en de ganse woning werd gerenoveerd volgens de eisen van de klant. De woonkamer kreeg een warme eiken vloer met ingebouwde spots. De eetkamer werd voorzien van designverlichting en nieuwe vloer. Een ingebouwde gashaard zorgt voor sfeer.',
    resultText: 'De woning is getransformeerd tot een moderne, warme leefomgeving. Het nieuwe dak garandeert jarenlange bescherming, terwijl het interieur nu de uitstraling heeft die past bij een kustresidentie. De combinatie van eiken vloeren, designmeubilair en sfeerverlichting maakt het geheel af.',
    mainImage: projectImages.oostende.main,
    images: {
      photos: projectImages.oostende.photos,
    },
  },
  {
    title: 'Afwerking Parijs',
    slug: 'afwerking-parijs',
    category: 'Renovatie',
    location: 'Parijs',
    year: 2025,
    featured: false,
    sortOrder: 3,
    projectType: 'Renovatie',
    duration: '2 maanden',
    surface: '75 m²',
    completionDate: '2025',
    shortDescription: 'Volledige afwerking van een Parijse appartement: vloeren, verlichting en schilderwerk.',
    challengeText: 'Dit appartement in Parijs was volledig gestript en klaar voor afwerking. De vloerbalken lagen bloot, de elektriciteit moest vernieuwd worden en de muren waren kaal. De eigenaar wilde een warme, moderne afwerking met karakter. Op vraag van een Franse professor hebben wij op twee maanden de ganse woning gerenoveerd. Ondanks de lange afstand en het feit dat wij de materialen uit Gent moesten transporteren, zijn wij erin geslaagd om deze woning om te toveren tot een aangename woning.',
    approachText: 'We begonnen met de elektrische installatie en het leggen van een prachtig eiken parket. De muren werden geschilderd, met als blikvanger een groene accentmuur in de woonkamer. Moderne railverlichting werd geïnstalleerd voor een strak en flexibel lichtplan. Elke ruimte kreeg zijn eigen sfeer.',
    resultText: 'Van een kale ruwbouw naar een stijlvol Parijs appartement. De combinatie van het eiken parket, de groene accentmuur en de railverlichting geeft het geheel een eigentijdse maar warme uitstraling. De eigenaar was bijzonder tevreden met het eindresultaat.',
    mainImage: projectImages.parijs.main,
    images: {
      before: projectImages.parijs.before,
      after: projectImages.parijs.after,
    },
  },
  {
    title: 'Reginald Warnefordstraat',
    slug: 'reginald-warnefordstraat',
    category: 'Totaalrenovatie',
    location: 'Gent',
    year: 2022,
    featured: true,
    sortOrder: 4,
    projectType: 'Totaalrenovatie',
    duration: '6 maanden',
    surface: '130 m²',
    completionDate: '2022',
    shortDescription: 'Stijlvolle totaalrenovatie in het hart van Gent met moderne keuken, stalen deuren en betonvloer.',
    challengeText: 'In een van de mooiste straten van Gent stond deze woning te wachten op een grondige renovatie. De eigenaars wilden een strakke, moderne woning met industriële accenten. De uitdaging was om een tijdloos design te creëren dat past in de historische omgeving.',
    approachText: 'We kozen voor een minimalistische aanpak met sterke materialen. Een moderne witte keuken met zwarte handgrepen en inbouwtoestellen vormt het hart van de woning. Stalen deuren met glas zorgen voor lichtinval en een industriële toets. De betonvloer geeft het geheel een stoere, eigentijdse uitstraling. Een apart keukeneiland met barkrukken maakt de leefruimte compleet.',
    resultText: 'Het resultaat is een woning die industrieel design combineert met huiselijk comfort. De witte keuken, stalen deuren en betonvloer vormen een harmonieus geheel. Dit project bewijst dat minimalisme en warmte perfect samengaan.',
    mainImage: projectImages.reginaldWarneford.main,
    images: {
      photos: projectImages.reginaldWarneford.photos,
    },
  },
  {
    title: 'Markt 6, Gavere',
    slug: 'markt-gavere',
    category: 'Ruwbouw',
    location: 'Gavere',
    year: 2024,
    featured: false,
    sortOrder: 5,
    projectType: 'Ruwbouw & Afbraak',
    duration: 'Lopend',
    surface: '220 m²',
    completionDate: 'Lopend',
    shortDescription: 'Grondige strip- en ruwbouwwerken van een historisch pand aan de Markt van Gavere.',
    challengeText: 'Dit historisch pand aan de Markt van Gavere moest volledig gestript worden tot op de draagstructuur. De zolderverdieping met originele houten spanten en bakstenen muren vormde een bijzondere uitdaging vanwege de leeftijd en staat van het gebouw.',
    approachText: 'We begonnen met een zorgvuldige afbraak, waarbij we de draagstructuur en originele houten spanten behielden. Alle vloeren, wanden en installaties werden gestript. De funderingen werden geïnspecteerd en waar nodig versterkt. Dit project wordt gefaseerd uitgevoerd om de structurele integriteit te waarborgen.',
    resultText: 'De stripfase is voltooid en het pand is klaar voor de volgende fase. De originele houten spanten op de zolder zijn behouden en zullen een uniek karakter geven aan het toekomstige interieur. Een project dat aantoont dat ook monumentale panden een tweede leven kunnen krijgen.',
    mainImage: projectImages.gavere.main,
    images: {
      photos: projectImages.gavere.photos,
    },
  },
  {
    title: 'Wasstraat',
    slug: 'wasstraat',
    category: 'Totaalrenovatie',
    location: 'Gent',
    year: 2025,
    featured: false,
    sortOrder: 6,
    projectType: 'Totaalrenovatie',
    duration: '7 maanden',
    surface: '145 m²',
    completionDate: '2025',
    shortDescription: 'Totaalrenovatie van een stadswoning in Gent: van ruwbouw tot moderne gezinswoning.',
    challengeText: 'Deze stadswoning in de Wasstraat in Gent ondergaat een volledige transformatie. Het bestaande pand werd volledig afgebroken tot op de funderingen. De uitdaging is om op deze locatie een moderne, energiezuinige gezinswoning te realiseren.',
    approachText: 'Na de afbraak en het uitgraven startten we met nieuwe funderingswerken inclusief DPC-folie en wapening. De ruwbouw wordt opgetrokken in rode baksteen. Alle leidingwerk voor sanitair en elektriciteit wordt in de muren ingewerkt. Dit project wordt gefaseerd uitgevoerd met aandacht voor de omliggende bebouwing.',
    resultText: 'Dit project is momenteel in uitvoering. De funderingen zijn gelegd, de ruwbouw is gevorderd en het leidingwerk wordt aangelegd. De voltooiing is gepland in 2025, wanneer deze stadswoning getransformeerd zal zijn tot een moderne gezinswoning.',
    mainImage: projectImages.wasstraat.main,
    images: {
      photos: projectImages.wasstraat.photos,
    },
  },
]
